export const types = {
    FETCH_INTERVIEW_ACCESS_LINK_REQUEST: 'FETCH_INTERVIEW_ACCESS_LINK_REQUEST',
    FETCH_INTERVIEW_ACCESS_LINK_SUCCESS: 'FETCH_INTERVIEW_ACCESS_LINK_SUCCESS',
    FETCH_INTERVIEW_ACCESS_LINK_FAILURE: 'FETCH_INTERVIEW_ACCESS_LINK_FAILURE',
  }