export const types = {
    FETCH_INTERVIEW_ACCESS_LINK_REQUEST: 'FETCH_INTERVIEW_ACCESS_LINK_REQUEST',
    FETCH_INTERVIEW_ACCESS_LINK_SUCCESS: 'FETCH_INTERVIEW_ACCESS_LINK_SUCCESS',
    FETCH_INTERVIEW_ACCESS_LINK_FAILURE: 'FETCH_INTERVIEW_ACCESS_LINK_FAILURE',

    FETCH_TRANSCRIBE_REQUEST: 'FETCH_TRANSCRIBE_REQUEST',
    FETCH_TRANSCRIBE_SUCCESS: 'FETCH_TRANSCRIBE_SUCCESS',
    FETCH_TRANSCRIBE_FAILURE: 'FETCH_TRANSCRIBE_FAILURE',

    UPDATE_INTERVIEW_REQUEST: 'UPDATE_INTERVIEW_REQUEST',
    UPDATE_INTERVIEW_SUCCESS: 'UPDATE_INTERVIEW_SUCCESS',
    UPDATE_INTERVIEW_FAILURE: 'UPDATE_INTERVIEW_FAILURE',

    FETCH_ANSWER_REQUEST: 'FETCH_ANSWER_REQUEST',
    FETCH_ANSWER_SUCCESS: 'FETCH_ANSWER_SUCCESS',
    FETCH_ANSWER_FAILURE: 'FETCH_ANSWER_FAILURE',
  }