export const types = {
    CREATE_INTERVIEW_REQUEST: 'CREATE_INTERVIEW_REQUEST',
    CREATE_INTERVIEW_SUCCESS: 'CREATE_INTERVIEW_SUCCESS',
    CREATE_INTERVIEW_FAILURE: 'CREATE_INTERVIEW_FAILURE',

    CREATE_INTERVIEW_TEMPLATE_REQUEST: 'CREATE_INTERVIEW_TEMPLATE_REQUEST',
    CREATE_INTERVIEW_TEMPLATE_SUCCESS: 'CREATE_INTERVIEW_TEMPLATE_SUCCESS',
    CREATE_INTERVIEW_TEMPLATE_FAILURE: 'CREATE_INTERVIEW_TEMPLATE_FAILURE',

    DELETE_INTERVIEW_REQUEST: 'DELETE_INTERVIEW_REQUEST',
    DELETE_INTERVIEW_SUCCESS: 'DELETE_INTERVIEW_SUCCESS',
    DELETE_INTERVIEW_FAILURE: 'DELETE_INTERVIEW_FAILURE',

    UPDATE_INTERVIEW_REQUEST: 'UPDATE_INTERVIEW_REQUEST',
    UPDATE_INTERVIEW_SUCCESS: 'UPDATE_INTERVIEW_SUCCESS',
    UPDATE_INTERVIEW_FAILURE: 'UPDATE_INTERVIEW_FAILURE',
    
    GET_INTERVIEWS_REQUEST: 'GET_INTERVIEWS_REQUEST',
    GET_INTERVIEWS_SUCCESS: 'GET_INTERVIEWS_SUCCESS',
    GET_INTERVIEWS_FAILURE: 'GET_INTERVIEWS_FAILURE',

    GET_INTERVIEW_REQUEST: 'GET_INTERVIEW_REQUEST',
    GET_INTERVIEW_SUCCESS: 'GET_INTERVIEW_SUCCESS',
    GET_INTERVIEW_FAILURE: 'GET_INTERVIEW_FAILURE',

    GET_INTERVIEW_TEMPLATES_REQUEST: 'GET_INTERVIEW_TEMPLATES_REQUEST',
    GET_INTERVIEW_TEMPLATES_SUCCESS: 'GET_INTERVIEW_TEMPLATES_SUCCESS',
    GET_INTERVIEW_TEMPLATES_FAILURE: 'GET_INTERVIEW_TEMPLATES_FAILURE',

    CHECK_INTERVIEW_REQUEST: 'CHECK_INTERVIEW_REQUEST',
    CHECK_INTERVIEW_SUCCESS: 'CHECK_INTERVIEW_SUCCESS',
    CHECK_INTERVIEW_FAILURE: 'CHECK_INTERVIEW_FAILURE',
  }