export const types = {
    CREATE_INTERVIEW_REQUEST: 'CREATE_INTERVIEW_REQUEST',
    CREATE_INTERVIEW_SUCCESS: 'CREATE_INTERVIEW_SUCCESS',
    CREATE_INTERVIEW_FAILURE: 'CREATE_INTERVIEW_FAILURE',
  }